services:
  web:
    build:
      dockerfile: Dockerfile.dev
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"

volumes:
  bundle_cache:
